// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseK8sResourceConfiguration) DeepCopyInto(out *BaseK8sResourceConfiguration) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8sResourceConfiguration.
func (in *BaseK8sResourceConfiguration) DeepCopy() *BaseK8sResourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(BaseK8sResourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfiguration) DeepCopyInto(out *ControllerConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfiguration.
func (in *ControllerConfiguration) DeepCopy() *ControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationConfiguration) DeepCopyInto(out *DestinationConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationConfiguration.
func (in *DestinationConfiguration) DeepCopy() *DestinationConfiguration {
	if in == nil {
		return nil
	}
	out := new(DestinationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeartbeatConfiguration) DeepCopyInto(out *HeartbeatConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeartbeatConfiguration.
func (in *HeartbeatConfiguration) DeepCopy() *HeartbeatConfiguration {
	if in == nil {
		return nil
	}
	out := new(HeartbeatConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityConfiguration) DeepCopyInto(out *IdentityConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityConfiguration.
func (in *IdentityConfiguration) DeepCopy() *IdentityConfiguration {
	if in == nil {
		return nil
	}
	out := new(IdentityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Linkerd) DeepCopyInto(out *Linkerd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Linkerd.
func (in *Linkerd) DeepCopy() *Linkerd {
	if in == nil {
		return nil
	}
	out := new(Linkerd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Linkerd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkerdList) DeepCopyInto(out *LinkerdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Linkerd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkerdList.
func (in *LinkerdList) DeepCopy() *LinkerdList {
	if in == nil {
		return nil
	}
	out := new(LinkerdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinkerdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkerdSpec) DeepCopyInto(out *LinkerdSpec) {
	*out = *in
	if in.AutoInjectionNamespaces != nil {
		in, out := &in.AutoInjectionNamespaces, &out.AutoInjectionNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Controller.DeepCopyInto(&out.Controller)
	in.Destination.DeepCopyInto(&out.Destination)
	in.Heartbeat.DeepCopyInto(&out.Heartbeat)
	in.Identity.DeepCopyInto(&out.Identity)
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	in.ProxyInit.DeepCopyInto(&out.ProxyInit)
	in.ProxyInjector.DeepCopyInto(&out.ProxyInjector)
	in.Tap.DeepCopyInto(&out.Tap)
	in.Web.DeepCopyInto(&out.Web)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkerdSpec.
func (in *LinkerdSpec) DeepCopy() *LinkerdSpec {
	if in == nil {
		return nil
	}
	out := new(LinkerdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkerdStatus) DeepCopyInto(out *LinkerdStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkerdStatus.
func (in *LinkerdStatus) DeepCopy() *LinkerdStatus {
	if in == nil {
		return nil
	}
	out := new(LinkerdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfiguration) DeepCopyInto(out *PrometheusConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfiguration.
func (in *PrometheusConfiguration) DeepCopy() *PrometheusConfiguration {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyInitConfiguration) DeepCopyInto(out *ProxyInitConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyInitConfiguration.
func (in *ProxyInitConfiguration) DeepCopy() *ProxyInitConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProxyInitConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyInjectorConfiguration) DeepCopyInto(out *ProxyInjectorConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyInjectorConfiguration.
func (in *ProxyInjectorConfiguration) DeepCopy() *ProxyInjectorConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProxyInjectorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapConfiguration) DeepCopyInto(out *TapConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapConfiguration.
func (in *TapConfiguration) DeepCopy() *TapConfiguration {
	if in == nil {
		return nil
	}
	out := new(TapConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebConfiguration) DeepCopyInto(out *WebConfiguration) {
	*out = *in
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebConfiguration.
func (in *WebConfiguration) DeepCopy() *WebConfiguration {
	if in == nil {
		return nil
	}
	out := new(WebConfiguration)
	in.DeepCopyInto(out)
	return out
}
