# permissions for end users to view linkerds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-viewer-role
rules:
- apiGroups:
  - linkerd.linkerd.io
  resources:
  - linkerds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - linkerd.linkerd.io
  resources:
  - linkerds/status
  verbs:
  - get
